[workspace]
members = [
    "crates/balansir-common",
    "crates/balansir-control",
    "crates/balansir-daemon",
    "crates/balansir-executor",
    "crates/balansir-api",
    "crates/balansir-tests",
]
resolver = "2"

[workspace.package]
version = "0.4.0"
edition = "2021"
authors = ["Egor Korostelev"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
tokio = { version = "1", default-features = false }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
postcard = { version = "1", features = ["alloc"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bytes = "1"
smallvec = { version = "1", features = ["serde"] }
bitflags = { version = "2", features = ["serde"] }
prometheus-client = "0.22"
axum = "0.7"
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
secrecy = { version = "0.10", features = ["serde"] }
zeroize = { version = "1", features = ["derive"] }
rtnetlink = "0.14"
netlink-packet-route = "0.19"
netlink-packet-core = "0.7"
libc = "0.2"
futures = "0.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false
