[package]
name = "balansir-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
balansir-common = { path = "../balansir-common" }
tokio = { workspace = true, features = ["rt", "net", "macros", "io-util"] }
postcard.workspace = true
smallvec.workspace = true

[lib]
name = "ipc_integration"
path = "src/ipc_integration.rs"
