[package]
name = "balansir-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true, features = ["net", "io-util"] }
postcard.workspace = true
thiserror.workspace = true
tracing.workspace = true
bytes.workspace = true
smallvec.workspace = true
bitflags.workspace = true
serde.workspace = true
