[package]
name = "balansir-vpn"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "balansir_vpn"

[dependencies]
balansir-health = { path = "../balansir-health" }
serde = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
