[package]
name = "balansir-daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["wireguard", "xray", "hysteria", "b4"]
wireguard = []
xray = []
hysteria = []
b4 = []
amneziawg = []
dns = []

[dev-dependencies]
tempfile = "3"
proptest = "1"

[dependencies]
balansir-common = { path = "../balansir-common" }
balansir-control = { path = "../balansir-control" }
tokio = { workspace = true, features = ["rt", "net", "macros", "io-util", "fs", "time", "signal"] }
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json = "1"
async-trait = "0.1"
smallvec.workspace = true
toml = "0.8"
which = "7"
postcard.workspace = true
uuid.workspace = true
libc.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
rtnetlink.workspace = true
netlink-packet-route.workspace = true
